package by.epam.halavin.maintask.controller.command;

public enum CommandNames {
    SIGN_IN, SIGN_OUT, REGISTER_IN, INIT_ADMIN, NEXT_PASSENGERS, NEXT_DRIVERS, EDIT_PASSENGER, EDIT_DRIVER, EMPTY_COMMAND,
    EN, RU, DRIVERSEARCH, COORDINATES, ACTIVATEDRIVER, DEACTIVATEDRIVER, REFRESH, CHECKTRIPS, ACCEPT, DECLINE, PAID,
    NEWDRIVERSEARCH, RESET,NEXT_BY_VALUE_DRIVERS,NEXT_BY_VALUE_PASSENGERS;
}
