package by.epam.halavin.maintask.controller.command;

public enum CommandNames {
    SIGN_IN, SIGN_OUT, REGISTER_IN_PASS, INIT_ADMIN, NEXT_PASSENGERS, NEXT_DRIVERS, EDIT_PASSENGER, EDIT_DRIVER, EMPTY_COMMAND,
    EN, RU, DRIVERSEARCH, COORDINATES, ACTIVATEDRIVER, DEACTIVATEDRIVER, REFRESH, CHECKTRIPS, ACCEPT, DECLINE, PAID,
    NEWDRIVERSEARCH, RESET,NEXT_BY_VALUE_DRIVERS,NEXT_BY_VALUE_PASSENGERS,GO_TO_ORDER,GO_TO_DRIVER,GO_TO_MAIN,
    REGISTER_IN_DRIVER, REFRESH_ADMIN_PAGE,GET_USER_ORDERS,CLOSE_USER_ORDERS;
}
