package by.epam.halavin.maintask.controller.command;

/**
 * Enum lists all command names.
 *
 * @author Ehor Halavin
 * @version 1.0
 */
public enum CommandNames {
    SIGN_IN, SIGN_OUT, REGISTER_IN_PASS, INIT_ADMIN, NEXT_PASSENGERS, NEXT_DRIVERS, EDIT_PASSENGER, EDIT_DRIVER, EMPTY_COMMAND,
    EN, RU, DRIVERSEARCH, COORDINATES, ACTIVATEDRIVER, DEACTIVATEDRIVER, REFRESH, CHECKTRIPS, ACCEPT, DECLINE, PAID,
    NEWDRIVERSEARCH, RESET,NEXT_BY_VALUE_DRIVERS,NEXT_BY_VALUE_PASSENGERS,GO_TO_ORDER,GO_TO_DRIVER,GO_TO_MAIN,
    REGISTER_IN_DRIVER, REFRESH_ADMIN_PAGE,GET_USER_ORDERS,CLOSE_USER_ORDERS,NEXT_BY_VALUE_ORDERS,AJAX_CUR_STREET;
}
